name: Sync with Upstream

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch and merge upstream changes
        run: |
          git remote add upstream https://github.com/smartcontractkit/chainlink.git
          git fetch upstream
          git checkout master
          git merge upstream/master
          # Handle merge conflicts if they occur
          # git mergetool -y (if you have a merge tool configured)
          # git commit -m "Merge upstream changes"
          git push origin master
